name: "Deploy Front-end"
description: "Build and deploys a versioned front-end of an application to an AWS S3 bucket"
inputs:
  app-name:
    description: "Name of application"
    required: true
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-access-key-secret:
    description: "AWS access key secret"
    required: true
  aws-s3-bucket:
    description: "Name of AWS S3 bucket"
    required: true
  aws-region:
    default: eu-west-1
    description: "AWS region for S3 bucket"
    required: true
  built-files:
    default: dist/
    description: "Directory where to find files to deploy once the project builds"
    required: true
  project-dir:
    default: .
    description: "Path to the front-end project, where package.json is located"
    required: true
  version:
    default: ${GITHUB_REF#refs/tags/}
    description: "Version to release; derived from tag name by default"
    required: true

runs:
  using: "composite"

  steps:
    - name: Validate version 👁
      id: validate
      shell: bash
      run: |
        INPUT_VERSION=${{ inputs.version }}

        if [[ ! "${INPUT_VERSION:0:1}" == 'v' ]]; then
          echo "Version does not start with 'v'; stopping"
          exit 1
        fi

        SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"

        if [[ ! "${INPUT_VERSION:1}" =~ $SEMVER_REGEX ]]; then
          echo "Version \"${INPUT_VERSION:1}\" is not SemVer compliant; see https://semver.org/"
          exit 1
        fi

        echo "::set-output name=version::${INPUT_VERSION:1}"

    - name: Checkout ⏬
      uses: actions/checkout@v2

    - name: Define Yarn 🧶 cache
      id: yarn-cache
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Activate Yarn 🧶 cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set up Node ⬢
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install dependencies ⏬
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Build 💪
      shell: bash
      run: yarn run build

    - name: Configure AWS Credentials 👮‍♀️
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-access-key-secret }}
        aws-region: ${{ inputs.aws-region }}

    - name: Copy files to S3 bucket 🔄
      shell: bash
      run: aws s3 sync ./${{ inputs.built-files }} s3://${{ inputs.aws-s3-bucket }}/${{ inputs.app-name }}/${{ steps.validate.outputs.version }}/
